### ISSUE TITLE
Support for graphql@15.3.0.

### ISSUE THREAD

**Issue by ccsv** [apollographql/apollo-link-persisted-queries#58]
npm audit fix shows that graphql version 15.3.0 is not supported

`npm WARN apollo-link-persisted-queries@0.2.2 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by kachkaev** [comment]
This should be fixed by #15. Looking at the commit history, it seems like the project is somewhat stale and the dependencies are quite out of date overall. Wondering is there already exists an alternative?

**2maintainers**: Happy to help with bumping all deps and switching to yarn if there is interest.
